// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from '/Users/bigger/Desktop/zhangbin/you-want/mlops-react-antd/node_modules/.pnpm/@umijs+renderer-react@4.0.87_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
