// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/bigger/Desktop/zhangbin/you-want/mlops-react-antd/node_modules/.pnpm/@ant-design+icons@4.8.1_biqbaboplfbrettd7655fr4n2y/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import HomeOutlined from '/Users/bigger/Desktop/zhangbin/you-want/mlops-react-antd/node_modules/.pnpm/@ant-design+icons@4.8.1_biqbaboplfbrettd7655fr4n2y/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import CrownOutlined from '/Users/bigger/Desktop/zhangbin/you-want/mlops-react-antd/node_modules/.pnpm/@ant-design+icons@4.8.1_biqbaboplfbrettd7655fr4n2y/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/Users/bigger/Desktop/zhangbin/you-want/mlops-react-antd/node_modules/.pnpm/@ant-design+icons@4.8.1_biqbaboplfbrettd7655fr4n2y/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, HomeOutlined, CrownOutlined, TableOutlined };
